// THIS FILE WAS AUTOGENERATED - ANY EDITS TO THIS WILL BE LOST WHEN IT IS REGENERATED




package generator

import (
	"github.com/relops/cqlc/meta"
)

func ParseValidator(validator string) (ColumnDataInfo, error) {
	switch validator {
		
		case "org.apache.cassandra.db.marshal.AsciiType": {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.AsciiType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.BooleanType": {
    		return ColumnDataInfo{DomainType: 6, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BooleanType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 6, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.BytesType": {
    		return ColumnDataInfo{DomainType: 12, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.BytesType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 12, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.CounterColumnType": {
    		return ColumnDataInfo{DomainType: 9, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.CounterColumnType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 9, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.DecimalType": {
    		return ColumnDataInfo{DomainType: 13, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DecimalType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 13, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.DoubleType": {
    		return ColumnDataInfo{DomainType: 4, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.DoubleType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 4, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.FloatType": {
    		return ColumnDataInfo{DomainType: 3, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 3, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.Int32Type": {
    		return ColumnDataInfo{DomainType: 1, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 1, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.LongType": {
    		return ColumnDataInfo{DomainType: 2, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.LongType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 2, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.TimeUUIDType": {
    		return ColumnDataInfo{DomainType: 7, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimeUUIDType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 7, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.TimestampType": {
    		return ColumnDataInfo{DomainType: 5, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 5, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.UTF8Type": {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 0, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
		case "org.apache.cassandra.db.marshal.UUIDType": {
    		return ColumnDataInfo{DomainType: 8, RangeType: meta.NoType, GenericType: meta.BasicType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: meta.NoType, GenericType: meta.SliceType}, nil
    	}

    	case "org.apache.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: meta.NoType, GenericType: meta.ReversedType}, nil
    	}

    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.AsciiType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.BooleanType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 6, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.BytesType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 12, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.CounterColumnType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 9, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.DecimalType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 13, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.DoubleType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 4, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.FloatType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 3, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.Int32Type)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 1, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.LongType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 2, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.TimeUUIDType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 7, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.TimestampType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 5, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.UTF8Type)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 0, GenericType: meta.MapType}, nil
    	}    		
    	
		case "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UUIDType,org.apache.cassandra.db.marshal.UUIDType)" : {
    		return ColumnDataInfo{DomainType: 8, RangeType: 8, GenericType: meta.MapType}, nil
    	}    		
    	

    	
    	default: {
    		return ColumnDataInfo{}, ErrTypeUnknown
    	}
	}
}