version: '3.3'
services:
  c2:
    image: 'cassandra:2.1'
    environment:
    - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
    ports:
    - target: 9042
      published: 9042
      protocol: tcp
  c3:
    image: 'cassandra:3.1'
    environment:
    - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
    ports:
    - target: 9042
      published: 9042
      protocol: tcp