.PHONY: run-c2 run-c3 shell-c2 shell-c3 down

run-c2:
	docker-compose up c2
run-c3:
	docker-compose up c3
shell-c2:
	docker-compose exec c2 /bin/bash
shell-c3:
	docker-compose exec c3 /bin/bash
down:
	docker-compose down
